# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Default

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |

    echo "Проверка работы агента:"
  displayName: 'Проверка окружения'
  
- task: PowerShell@2
  name: notify_telegram
  displayName: "📢 Уведомление в Telegram"
  inputs:
    targetType: 'inline'
    script: |
      # Получаем статус сборки
      $status = if ("$(Agent.JobStatus)" -eq "Succeeded") { "✅" } else { "❌" }
      
      # Формируем сообщение
      $message = @"
      $status Pipeline: <b>$(Build.DefinitionName)</b>
      Branch: <code>$(Build.SourceBranchName)</code>
      Build: <a href='$(System.CollectionUri)$(System.TeamProject)/_build/results?buildId=$(Build.BuildId)'>#$(Build.BuildNumber)</a>
      "@
      
      # Альтернативное кодирование URL (без System.Web)
      $encodedMessage = $message -replace ' ', '%20' -replace '<', '%3C' -replace '>', '%3E'
      
      # Отправляем в Telegram
      $url = "https://api.telegram.org/bot7802544152:AAFej-O8UOM3dce3HG0Vc8BEx7qZA_ZdvhQ/sendMessage?chat_id=-4729697131&parse_mode=HTML&text=$encodedMessage"
      try {
        Invoke-RestMethod -Uri $url -Method Get
        Write-Host "Уведомление отправлено!"
      } catch {
        Write-Host "Ошибка отправки: $_"
      }
  condition: always()