# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Default

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |

    echo "Проверка работы агента:"
  displayName: 'Проверка окружения'
  
- task: PowerShell@2
  name: notify_telegram
  displayName: "📢 Уведомление в Telegram"
  inputs:
    targetType: 'inline'
    script: |
      # Формируем статус
      $status = if ("$(Agent.JobStatus)" -eq "Succeeded") { "✅ УСПЕХ" } else { "❌ ОШИБКА" }
      
      # Создаем простое текстовое сообщение (без HTML)
      $message = @"
      $status
      Pipeline: $(Build.DefinitionName)
      Ветка: $(Build.SourceBranchName)
      Сборка: #$(Build.BuildNumber)
      Ссылка: $(System.CollectionUri)$(System.TeamProject)/_build/results?buildId=$(Build.BuildId)
      "@
      
      # Кодируем только специальные символы
      $encodedMessage = [System.Uri]::EscapeDataString($message)
      
      # Отправляем
      $url = "https://api.telegram.org/bot7802544152:AAFej-O8UOM3dce3HG0Vc8BEx7qZA_ZdvhQ/sendMessage?chat_id=-4729697131&text=$encodedMessage"
      try {
        $response = Invoke-RestMethod -Uri $url
        Write-Host "Уведомление отправлено: $($response | ConvertTo-Json -Depth 3)"
      } catch {
        Write-Host "Ошибка: $($_.Exception.Message)"
        Write-Host "Подробности: $($_.Exception.Response | ConvertTo-Json -Depth 3)"
      }
  condition: always()